---
- name: Deploy Laravel Project
  hosts: webserver
  vars:
    student_name: "sav-moeng" 
    app_path: "/var/www/{{ student_name }}"

  tasks:
    - name: Ensure the directory exists
      file:
        path: "{{ app_path }}"
        state: directory
        mode: '0755'

    - name: Archive project locally
      delegate_to: localhost
      shell: tar -czf /tmp/project.tar.gz . --exclude=.git --exclude=node_modules --exclude=vendor

    - name: Upload and Extract
      unarchive:
        src: /tmp/project.tar.gz
        dest: "{{ app_path }}"
        owner: www-data
        group: www-data